syntax = "proto3";
option optimize_for = LITE_RUNTIME;
enum GameComponentTypeMessage{
  COMPONENT_NONE = 0;
  COMPONENT_AREA_MARKER = 1;
  COMPONENT_AUTO_PICK = 2;
  COMPONENT_BLUEPRINT = 3;
  COMPONENT_CAMERA = 4;
  COMPONENT_DEBUG_DRAW = 5;
  COMPONENT_DIGGING = 6;
  COMPONENT_DRAGGABLE = 7;
  COMPONENT_DROPPED_ITEM = 8;
  COMPONENT_FLOATING_TEXT = 9;
  COMPONENT_HOT_BAR = 11;
  COMPONENT_ITEM_CONTAINER = 12;
  COMPONENT_ITEM_EDITOR = 13;
  COMPONENT_ITEM_SLOT = 14;
  COMPONENT_MAGNET = 15;
  COMPONENT_MAGNETIC = 16;
  COMPONENT_MOB = 17;
  COMPONENT_PARALLAX_BACKGROUND = 18;
  COMPONENT_PAUSE = 19;
  COMPONENT_PLAYER = 20;
  COMPONENT_RAY_CAST_2D = 21;
  COMPONENT_RIGID_BODY_2D = 22;
  COMPONENT_SPIRIT_RENDERER = 23;
  COMPONENT_TILE_LAYER = 24;
  COMPONENT_TILE_PLACEMENT_FORBIDDEN_ZONE = 25;
  COMPONENT_TRANSFORM_2D = 26;
  COMPONENT_CRAFT_PREVIEW = 27;
  COMPONENT_BUTTON = 28;
  COMPONENT_ITEM_TOOL_TIP = 29;
  COMPONENT_ITEM_SLOT_QUANTITY = 30;
  COMPONENT_TECH_PROVIDER = 31;
}