syntax = "proto3";
option optimize_for = LITE_RUNTIME;
enum GameComponentTypeMessage{
    COMPONENT_NONE = 0;
    COMPONENT_AREA_MARKER = 1;
    COMPONENT_AUTO_PICK = 2;
    COMPONENT_BLUEPRINT = 3;
    COMPONENT_CAMERA = 4;
    COMPONENT_DEBUG_DRAW = 5;
    COMPONENT_DROPPED_ITEM = 6;
    COMPONENT_FLOATING_TEXT = 7;
    COMPONENT_ITEM_CONTAINER = 8;
    COMPONENT_ITEM_EDITOR = 9;
    COMPONENT_ITEM_TOOL_TIP = 10;
    COMPONENT_MAGNET = 11;
    COMPONENT_MAGNETIC = 12;
    COMPONENT_MINING = 13;
    COMPONENT_MOB = 14;
    COMPONENT_PARALLAX_BACKGROUND = 15;
    COMPONENT_PAUSE = 16;
    COMPONENT_PLAYER = 17;
    COMPONENT_RAY_CAST_2D = 18;
    COMPONENT_RECIPE_SELECTION = 19;
    COMPONENT_RIGID_BODY_2D = 20;
    COMPONENT_SPIRIT_RENDERER = 21;
    COMPONENT_TECH_PROVIDER = 22;
    COMPONENT_TILE_LAYER = 23;
    COMPONENT_TILE_PLACEMENT_FORBIDDEN_ZONE = 24;
    COMPONENT_TRANSFORM_2D = 25;
    COMPONENT_LIGHT = 26;
};