syntax = "proto3";
option optimize_for = LITE_RUNTIME;
import "src/saves/entity_item.proto";
import "src/saves/transform2d.proto";
import "src/core/resource_ref.proto";
message PlayerDimensionMessage{
  //The coordinate transformation information when the player leaves this dimension, and when re-entering the dimension, the player will be restored to this position.
  //玩家离开该维度时的坐标变换信息，重新进入维度时将玩家恢复到此位置
  Transform2dMessage lastTransform = 1;
  ResourceRefMessage dimension = 2;
  //Should the game automatically set a starting point for the player?
  //是否需要让游戏自动为玩家设置一个出生点。
  bool needAutomaticSpawn = 3;
}