syntax = "proto3";
option optimize_for = LITE_RUNTIME;
enum ResourceTypeMessage{
  RESOURCE_NONE = 0;
  RESOURCE_STRING = 1;
  RESOURCE_TILE = 2;
  RESOURCE_COMPOSABLE_ITEM = 3;
  RESOURCE_ABILITY_ITEM = 4;
  RESOURCE_LOOT_TABLE = 5;
  RESOURCE_STRUCTURE = 6;
  RESOURCE_TEXTURE = 7;
  RESOURCE_BIOME = 8;
  RESOURCE_COLOR = 9;
  RESOURCE_MOB = 10;
  RESOURCE_SHAPE = 11;
  RESOURCE_AUDIO = 12;
  //This dropped item resource type is used for serialization within the game save file. Currently, this type of resource is not supported for definition within the mod.
  //这个掉落物资源类型用作存档内序列化。模组内暂不支持定义此类型的资源。
  RESOURCE_DROPPED_ITEM = 13;
  RESOURCE_BIOME_DECORATOR = 14;
  RESOURCE_FIXED_COLOR = 15;
  RESOURCE_LIGHT_SOURCE = 16;
  RESOURCE_LIGHT_MASK = 17;
  RESOURCE_TREE_STRUCTURE = 18;
  RESOURCE_STATIC_STRUCTURE = 19;
  RESOURCE_MATERIAL_ITEM = 20;
  RESOURCE_RML_PATH = 21;
  RESOURCE_STRUCTURE_PLACEMENT_CONDITIONS = 22;
  //Vertex Shader
  //顶点着色器
  RESOURCE_SHADER_VERTEX = 23;
  //Fragment (Subsection) Shader
  //片元(片段)着色器
  RESOURCE_SHADER_FRAGMENT = 24;
  RESOURCE_PIPELINE = 25;
  RESOURCE_SAMPLER = 26;
  //Unified variable buffer(To be passed on to the Shader)
  //统一变量缓冲区（用于传递给Shader）
  RESOURCE_UNIFORM_BLOCK = 27;
  //Dimension
  //维度
  RESOURCE_DIMENSION = 28;
}
