syntax = "proto3";
option optimize_for = LITE_RUNTIME;
enum ResourceTypeMessage{
  None = 0;
  String = 1;
  Tile = 2;
  ComposableItem = 3;
  AbilityItem = 4;
  LootTable = 5;
  StaticStructure = 6;
  Texture = 7;
  Biome = 8;
  Color = 9;
  Mob = 10;
  Shape = 11;
  Audio = 12;
  //This dropped item resource type is used for serialization within the game save file. Currently, this type of resource is not supported for definition within the mod.
  //这个掉落物资源类型用作存档内序列化。模组内暂不支持定义此类型的资源。
  DroppedItem = 13;
  BiomeDecorator = 14;
  FixedColor = 15;
  LightSource = 16;
  LightMask = 17;
  TreeStructure = 18;
}